### ISSUE TITLE
Does not compile on MacOS

### ISSUE THREAD

**Issue by Byron** [Exotik850/cleave#2]
On MacOS in a fresh clone, I tried `cargo run`, but the compilation failed with:

```
error[E0432]: unresolved import `winit::platform::windows`
  --> src/context.rs:7:34
   |
7  |     dpi::PhysicalSize, platform::windows::IconExtWindows, window::{Icon, Window, WindowAttributes}
   |                                  ^^^^^^^ could not find `windows` in `platform`
   |
note: found an item that was configured out
  --> /Users/byron/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform/mod.rs:20:9
   |
20 | pub mod windows;
   |         ^^^^^^^
note: the item is gated here
  --> /Users/byron/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform/mod.rs:19:1
   |
19 | #[cfg(any(windows_platform, docsrs))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `GenericImageView`
 --> src/context.rs:4:13
  |
4 | use image::{GenericImageView, ImageBuffer, Rgba};
  |             ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0432`.
warning: `cleave` (bin "cleave") generated 1 warning
error: could not compile `cleave` (bin "cleave") due to 1 previous error; 1 warning emitted
```

My recommendation is to setup CI to create builds on Linux at least.

**Comment by kenielf** [comment]
Issue also applies to Linux, exact same type of error message, with cargo version as: `1.82.0 (8f40fc59f 2024-08-21)`

# Edit
By using a bit of conditional compilation, I have managed to get the software to compile, on `src/context.rs`, you can switch the use parameters for winit in the following manner:

```rs
#[cfg(target_os = "windows")]
use winit::{
    dpi::PhysicalSize, platform::windows::IconExtWindows, window::{Icon, Window, WindowAttributes}
};
#[cfg(not(target_os = "windows"))]
use winit::{
    dpi::PhysicalSize, window::{Icon, Window, WindowAttributes}
};
```

This is because the trait [IconExtWindows](https://docs.rs/winit/latest/winit/platform/windows/trait.IconExtWindows.html) only applies to Windows.

After applying this change, I was able to compile, run and "take" a screenshot, however it crashes with an invalid selection size error: `Invalid selection size (850, 397, 338300) (w h p)`

**Comment by jeffjose** [comment]
Same error on Linux as well.

```
$ uname -a
Linux skyfall 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Exotik850** [comment]
I do not have a linux machine but i've removed the trait as it wasn't needed, also put in some rounding fixes so please let me know if that has fixed the issue

**Comment by kenielf** [comment]
@Exotik850 The new patch compiles fine, but the invalid selection size error persists.

**Comment by Exotik850** [comment]
Ah, [these lines here are most likely the issue](https://github.com/Exotik850/cleave/blob/dd7215483b35118f10897f5ceb95491d4ba7f788/src/context.rs#L93C12-L93C57)
```rust
   let width = width.floor() as usize;
   let height = height.floor() as usize;
   // ...
   if selection.area() as usize != image_data.len() / 4 {
```

Uploaded another patch

**Comment by kenielf** [comment]
@Exotik850 works on/off, depends on the area selected.

Copying to the actual clipboard will require separate implementations, for macos and both graphical backends on linux (x11 and wayland)
```bash
$ ./target/release/cleave 
Invalid selection size (936, 436, 407160) (w h p)
$ ./target/release/cleave 
Invalid selection size (1318, 554, 728301) (w h p)
$ ./target/release/cleave 
Invalid selection size (659, 491, 322910) (w h p)
$ ./target/release/cleave 
$ ./target/release/cleave 
$ ./target/release/cleave 
$ ./target/release/cleave 
Invalid selection size (724, 360, 260280) (w h p)
$ ./target/release/cleave 
Invalid selection size (1040, 608, 630673) (w h p)
$ ./target/release/cleave 
Invalid selection size (992, 384, 379936) (w h p)
$ ./target/release/cleave 
Invalid selection size (924, 663, 611688) (w h p)
$ ./target/release/cleave 
$ ./target/release/cleave 
Invalid selection size (1000, 501, 499500) (w h p) 
```

**Comment by Exotik850** [comment]
Well, since the original issue is resolved I'll close this, please open a new issue with your OS info as well if you don't mind

**Comment by kenielf** [comment]
> Well, since the original issue is resolved I'll close this, please open a new issue with your OS info as well if you don't mind

Yeah, no worries, I'll open an issue and fork the repository and try to implement a decent solution in regards to the multi-platform clipboards later in the evening as well.
