### ISSUE TITLE
Thick selection border obfuscates selection

### ISSUE THREAD

**Issue by orlp** [Exotik850/cleave#4]
If you're doing fine adjustments the thick rainbow border can make it hard to see what you're selecting exactly. I think the display used by the cursor-based selection is far superior. Perhaps to indicate the cursor selection is done add a small dashed border? Mockup:
![image](https://github.com/user-attachments/assets/75186326-ea05-4b35-a24f-039cf0044a4b)

**Comment by Exotik850** [comment]
In the future I plan on having a customizable selection and drag design system so this is kind of on the back burner for now. In the original versions of the program it was simply a white rectangle so I hobbled together the rainbow outline for minimal aesthetic, but I can see how it'd be hard to tell what's being selected.

**Comment by orlp** [comment]
> customizable selection and drag design system

Going to be real with you here: no one wants that. People want good defaults out-of-the-box because no one is going to bother with customizing their screenshot grabber.

**Comment by Exotik850** [comment]
I'm adding it regardless - it's a feature I personally want. While good defaults are important, I believe programs feel incomplete without giving users customization options. This is something I value in software, so it's staying in my plans.

**Comment by orlp** [comment]
Oh sure, don't let me stop you from also adding customization (my message was probably a bit too negative), just saying they're not an alternative for good defaults :)

**Comment by Exotik850** [comment]
Fixed with [this commit](https://github.com/Exotik850/cleave/commit/e764a1365f62e03852077c77dc78eb5374f550ac)
