### ISSUE TITLE
Re-selecting region temporarily connects to outdated selection corner

### ISSUE THREAD

**Issue by orlp** [Exotik850/cleave#5]
Steps to reproduce:

1. Start cleave.
2. Create a selection with the mouse.
3. Start a second selection with the mouse, but don't move the mouse yet.

Now the new region is connected to the bottom-right corner of the old region until you move the mouse:

![image](https://github.com/user-attachments/assets/8632ab7e-9e1b-477d-b1ae-0cf5908eaa3e)

**Comment by Exotik850** [comment]
Fixed with [this commit](https://github.com/Exotik850/cleave/commit/f00ad013aeb4456ff82a9308657085d5fbc3488a)
