### ISSUE TITLE
What capture API does this use?

### ISSUE THREAD

**Issue by Quackdoc** [Exotik850/cleave#8]
Specifying capture APIs is important on linux as this tool for instance does not work on cosmic-compositor

**Comment by Quackdoc** [comment]
Seems like this uses xcap which supports gnome's screenshot or portals. Portals should be working, Im hitting a different issue, will try and find out what it is, will leave this open since it's necessary anyways.

**Comment by Exotik850** [comment]
Updated the readme in [this commit](https://github.com/Exotik850/cleave/commit/48de250b68d5237146f7a39dcea7dbcc951d799e) with linux details
