### ISSUE TITLE
How to use with a keyboard shortcut?

### ISSUE THREAD

**Issue by Devesh-N** [Exotik850/cleave#9]
Hey! Currently cleave only screenshots when I enter cleave in the terminal. I wanted to know how I might be able to bind it to a keyboard shortcut.
Thanks.

**Comment by Exotik850** [comment]
It should be as easy as throwing the contents of [`fn main`](https://github.com/Exotik850/cleave/blob/48de250b68d5237146f7a39dcea7dbcc951d799e/src/main.rs#L160) into another function and using a crate like [`global_hotkey`](https://docs.rs/crate/global-hotkey/latest) to listen for the hotkey that you want, or if you didnt wanna change the application at all you can just use something like autohotkey to launch the program on a keybind

**Comment by Devesh-N** [comment]
> It should be as easy as throwing the contents of [`fn main`](https://github.com/Exotik850/cleave/blob/48de250b68d5237146f7a39dcea7dbcc951d799e/src/main.rs#L160) into another function and using a crate like [`global_hotkey`](https://docs.rs/crate/global-hotkey/latest) to listen for the hotkey that you want, or if you didnt wanna change the application at all you can just use something like autohotkey to launch the program on a keybind

I don't know rust so I'll use the auto hot key bind
